agent: "QTRAN_base"  # Options: QTRAN_base, QTRAN_alt
env_id: "simple_spread_v2"
policy: "Qtran_Mixing_Q_network"
representation: "Basic_MLP"
vectorize: "Dummy_MAS"
runner: "MARL"

representation_hidden_size: [256, ]
q_hidden_size: [256, ]  # the units for each hidden layer
qtran_net_hidden_dim: 64
lambda_opt: 1.0
lambda_nopt: 1.0

buffer_size: 100000
batch_size: 256
learning_rate: 0.001
gamma: 0.95  # discount factor

start_greedy: 0.0
end_greedy: 0.95
greedy_update_steps: 5000
training_steps: 20000
training_frequency: 1
sync_frequency: 200

n_tests: 5
test_period: 100
double_q: True  # use double q learning
consider_terminal_states: False  # if consider the terminal states when calculate target Q-values.

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

logdir: "./logs/qtran"
modeldir: "./models/qtran"
