agent: "MPDQN"
env_id: "Platform-v0"
policy: "MPDQN_Policy"
representation: "Basic_MLP"

representation_hidden_size: [128,]
conactor_hidden_size: [128,]
qnetwork_hidden_size: [128, ]

nsize: 20000
batchsize: 128
learning_rate: 0.001
gamma: 0.99
tau: 0.005

start_noise: 0.1
end_noise: 0.1
training_frequency: 1
training_steps: 30000
start_training: 1000

use_obsnorm: False
use_rewnorm: False
obsnorm_range: 5
rewnorm_range: 5

logdir: "./logs/mpdqn"
modeldir: "./models/mpdqn"

vectorize: NOREQUIRED
